spring:
  datasource:
    url: jdbc:postgresql://rogue.db.elephantsql.com/yyqwxdxx
    username: yyqwxdxx
    password: LBziLVNYPqY1aFKPetsnilGZ0qwv1y2N
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
